### ISSUE TITLE
Missing obj files

### ISSUE THREAD

**Issue by gameblabla** [SciArt/Voxer#1]
Hello,
it seems that the .obj files required to run the game are missing.
I wanted to do a port to Linux but noticed they were missing for the prebuilt windows version here too.
So we can't actually run the game :/

**Comment by SciArt** [comment]
Hi,
Thank you for reporting the issue. 
The problem was that .gitignore was excluding all .obj files. I didn't notice this when I uploaded the project.
I added missing .obj files. Let me know if everything works.

**Comment by gameblabla** [comment]
Hey, thanks ! It works now. I was working on a Linux port and eventually porting it to the GCW0/RG350 as well with gl4es.
I ported other games like Stunt Car Racer and Pacman Arena to said console like this and was looking for more potential candidates (games that were either OpenGL 1/2 or GLESv1/v2).
I thought it was a cool little game and it was worth porting.
Here's my source code and linux branch : https://github.com/gameblabla/Voxer/commits/linux_port
